language: node_js

dist: xenial

services:
  - xvfb

##### WARNING
# node-pre-gyp tests are not concurrency safe
# such that in the below travis builds we cannot
# have more than one run with the same node version
# otherwise they will clobber each other
#####

matrix:
  include:
    # Test node v10 with request override
    - os: linux
      node_js: 10
      before_install:
        - npm install request

    # Test node v14 with request override
    - os: linux
      node_js: 12
      before_install:
        - npm install request

    # Test node v14 with request override
    - os: linux
      node_js: 14
      before_install:
        - npm install request

    # Test node webkit
    - os: linux
      node_js: 10
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: ['xvfb','libasound2','libx11-6','libglib2.0-0','libgtk2.0-0','libatk1.0-0','libgdk-pixbuf2.0-0','libcairo2','libfreetype6','libfontconfig1','libxcomposite1','libasound2','libxdamage1','libxext6','libxfixes3','libnss3','libnspr4','libgconf-2-4','libexpat1','libdbus-1-3','libudev1']
      script:
        # test node-webkit usage
        - ./scripts/test-node-webkit.sh

install:
- npm install

script:
- npm test
